version: "3"
services:
  node:
    image: node:18
    working_dir: /usr/src/app
    tty: true
    ports:
    - '3000:3000'
    volumes:
      - ./:/usr/src/app
    command: >
      bash -c "npm install &&
      npm install nodemon -g &&
      nodemon src/server.js"
    depends_on:
      - db
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
    volumes:
      - ./docker/storage/data:/data
  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=develop
      - MYSQL_ROOT_PASSWORD=pass
      - TZ=Asia/Tokyo

volumes:
  db-store: