version: "3"
services:
  node:
    image: node:18
    working_dir: /usr/src/app
    tty: true
    ports:
    - '3000:3000'
    volumes:
      - ./:/usr/src/app
    command: >
      bash -c "npm install &&
      npm install nodemon -g &&
      nodemon src/server.js"
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
    volumes:
      - ./docker/storage/data:/data
